Fix GET /cdns/routing endpoint (#6363)
Without this, we get the following error:

  ERROR: api.go:253: 2021-11-19T21:02:45.081842Z: [::1]:53397 getting
  monitors: querying routers: pq: got 1 parameters but the statement
  requires 0